spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://localhost:8071

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"