spring:
  application:
    name: eurekaserver
  config:
    import: optional:configserver:http://localhost:8071
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: rabbit
      rabbitmq:
        queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"