spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Banking accounts related QA APIs "
  contactDetails:
    name: "Vibhushit Singhal - QA Lead"
    email: "vibhushit@developer.com"
  onCallSupport:
    - (666) 555-1234
    - (666) 523-1345