spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

  application:
    name: accounts
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: Accounts Microservice
    description: Vibhushit's Bank Account Application
    version: 1.0.0

endpoints:
  shutdown:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      detailsForCustomerSupportApp:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      retryForCustomerDetails:
        maxRetryAttempts: 3
        waitDuration: 2000
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      sayHello:
        timeoutDuration: 5000
        limitRefreshPeriod: 5000
        limitForPeriod: 1