services:
  network-deploy-service:
    networks:
      - banking_system

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_PRROFILES_ACTIVE: default
      
  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on: 
      configserver:
        condition: service_completed_successfully
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"