#version: "3.8"
#
#services:
#
#  configserver:
#    image: vibhushit0702/vibhushit0702-configserver:latest
#    mem_limit: 700m
#    ports:
#      - "8071:8071"
#    networks:
#      - vibhushit0702
#
#  eurekaserver:
#    image: vibhushit0702/vibhushit0702-eurekaserver
#    mem_limit: 700m
#    ports:
#      - "8070:8070"
#    networks:
#      - vibhushit0702
#    depends_on:
#      - configserver
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 15s
#        max_attempts: 5
#        window: 120s
#    environment:
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#
#  accounts:
#    image: vibhushit0702/vibhushit0702-accounts:latest
#    mem_limit: 700m
#    ports:
#      - "8080:8080"
#    networks:
#      - vibhushit0702
#    depends_on:
#      - configserver
#      - eurekaserver
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 5
#        window: 120s
#    environment:
#      SPRING_APPLICATION_NAME: accounts
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
#
##  accounts1:
##    image: vibhushit0702/vibhushit0702-accounts:latest
##    mem_limit: 700m
##    ports:
##      - "9090:8080"
##    networks:
##      - vibhushit0702
##    depends_on:
##      - configserver
##      - eurekaserver
##    deploy:
##      restart_policy:
##        condition: on-failure
##        delay: 30s
##        max_attempts: 5
##        window: 120s
##    environment:
##      SPRING_APPLICATION_NAME: accounts
##      SPRING_PROFILES_ACTIVE: default
##      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
##      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
#
#  loans:
#    image: vibhushit0702/vibhushit0702-loans:latest
#    mem_limit: 700m
#    ports:
#      - "8081:8081"
#    networks:
#      - vibhushit0702
#    depends_on:
#      - configserver
#      - eurekaserver
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 5
#        window: 120s
#    environment:
#      SPRING_APPLICATION_NAME: loans
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
#
#  cards:
#    image: vibhushit0702/vibhushit0702-cards:latest
#    mem_limit: 700m
#    ports:
#      - "8082:8082"
#    networks:
#      - vibhushit0702
#    depends_on:
#      - configserver
#      - eurekaserver
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 30s
#        max_attempts: 5
#        window: 120s
#    environment:
#      SPRING_APPLICATION_NAME: cards
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
#
#  gatewayserver:
#    image: vibhushit0702/vibhushit0702-gatewayserver:latest
#    mem_limit: 700m
#    ports:
#      - "8072:8072"
#    networks:
#      - vibhushit0702
#    depends_on:
#      - configserver
#      - eurekaserver
#      - cards
#      - loans
#      - accounts
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 45s
#        max_attempts: 5
#        window: 180s
#    environment:
#      SPRING_APPLICATION_NAME: gatewayserver
#      SPRING_PROFILES_ACTIVE: default
#      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
#
#networks:
#  vibhushit0702: